spring:
  application:
    name: currency-exchange-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: avar
    password: mittal
  h2:
    console:
      enabled: true
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


#Circut Breaker configurations
resilience4j:
  retry:
    instance:
      sampleApi:
        maxRetryAttempts: 10
        waitDuration: 2s
        enableExponentialBackoff: true
#Rate Limiter configs
  rateLimiter:
    instances:
      rateLim:
        limitForPeriod: 2
        limitRefreshPeriod: 10s

#BulkHead Configs
  bulkHead:
    instances:
      bulkHead:
        maxConcurrentCalls: 2
